name       : hexchat
version    : 2.14.3
release    : 32
homepage   : https://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.14.3.tar.xz : 901a9d13db5a4da69b827f6093306bbd16863dc49016f7668bd3e4506512e882
license    : GPL-2.0-or-later
component  :
    - network.irc
    - theme-manager : network.irc
summary    :
    - GTK+ IRC client
    - theme-manager : A theme manager for the hexchat IRC client
description:
    - HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
    - theme-manager : A theme manager for the hexchat IRC client
patterns   :
    - theme-manager :
        - /usr/bin/thememan*
        - /usr/share/applications/io.github.Hexchat.ThemeManager.desktop
        - /usr/share/mime/packages/io.github.Hexchat.ThemeManager.xml
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libpci)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - mono-msbuild
rundeps    :
    - enchant
    - theme-manager :
        - hexchat
        - mono
setup      : |
    %patch -p1 < $pkgfiles/0001-common-cfgfiles-Apply-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0002-Default-to-Solus.patch
    %patch -p1 < $pkgfiles/0003-Use-pango_font_metrics_get_height-to-calculate-font-height.patch
    %meson_configure -Dwith-theme-manager=true
build      : |
    %ninja_build
install    : |
    %ninja_install
