name       : hexchat
version    : 2.12.2
release    : 7
homepage   : http://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.12.2.tar.xz : 6dad783f37aac32a8301a12d498af7a74900f011aec4e77bb378ae9797a3ccf6
license    : GPL-2.0
summary    : GTK2 IRC Client
component  : network.irc
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(lua-5.1)
    - pkgconfig(luajit)
    - pkgconfig(atk)
    - pkgconfig(pangocairo)
    - pkgconfig(atspi-2)
    - gnome-common
description: HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
