name       : hexchat
version    : 2.16.1
release    : 42
homepage   : https://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.16.1.tar.xz : a7e497da71df419daf9855582d51c723a2611de25d5e97b5efc33fe78da5c4c7
license    : GPL-2.0-or-later
component  :
    - network.irc
    - theme-manager : network.irc
summary    :
    - GTK+ IRC client
    - theme-manager : A theme manager for the hexchat IRC client
description:
    - HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
    - theme-manager : A theme manager for the hexchat IRC client
patterns   :
    - theme-manager :
        - /usr/bin/thememan*
        - /usr/share/applications/io.github.Hexchat.ThemeManager.desktop
        - /usr/share/mime/packages/io.github.Hexchat.ThemeManager.xml
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(iso-codes)
    - pkgconfig(libcanberra)
    - pkgconfig(libpci)
    - pkgconfig(luajit)
    - pkgconfig(python3-embed)
    - mono-msbuild
    - python-cffi
rundeps    :
    - enchant
    - gtk2-engine-murrine
    - python-cffi
    - theme-manager :
        - hexchat
        - mono
setup      : |
    %apply_patches
    %meson_configure -Dtheme-manager=true
build      : |
    %ninja_build
install    : |
    %ninja_install
