name       : hexchat
version    : 2.14.1
release    : 16
homepage   : https://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.14.1.tar.xz : b032e4bcebe2229f87047439979a1246ddcbf599e7e538baa3f2abfac9a003a2
license    : GPL-2.0
component  : network.irc
summary    : GTK+ IRC client
description: HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libpci)
    - pkgconfig(luajit)
    - pkgconfig(python3)
rundeps    :
    - enchant
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
