name       : hexchat
version    : 2.14.3
release    : 25
homepage   : https://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.14.3.tar.xz : 901a9d13db5a4da69b827f6093306bbd16863dc49016f7668bd3e4506512e882
license    : GPL-2.0-or-later
component  : network.irc
summary    : GTK+ IRC client
description: HexChat is an IRC client based on XChat, but unlike XChat it’s completely
    free for both Windows and Unix-like systems.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libpci)
    - pkgconfig(luajit)
    - pkgconfig(python3)
rundeps    :
    - enchant
setup      : |
    %patch -p1 < $pkgfiles/0001-common-cfgfiles-Apply-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0001-Default-to-Solus.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
