name       : hexchat
version    : 2.12.0
release    : 5
homepage   : http://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.12.0.tar.xz : c2072f97510c0fe6ecfb0878750d27179633e08199066972fa00e5a23e67d69d
license    : GPL-2.0
summary    : GTK2 IRC Client
component  : network.irc
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(atk)
    - pkgconfig(pangocairo)
    - pkgconfig(atspi-2)
    - gnome-common
description: 
    HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems. 
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
