name       : hexchat
version    : 2.10.2
release    : 1
homepage   : http://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.10.2.tar.xz : 87ebf365c576656fa3f23f51d319b3a6d279e4a932f2f8961d891dd5a5e1b52c
license    : GPLv2
clang      : yes
summary    : GTK2 IRC Client
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(atk)
    - pkgconfig(pangocairo)
    - pkgconfig(atspi-2)
    - gnome-common
description: 
    HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems. 
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
