name       : hexchat
version    : 2.12.4
release    : 10
homepage   : http://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.12.4.tar.xz : fa35913158bbc7d0d99de79371b6df3e8d21802f1d2c7c92f0e5db694acf2c3a
license    : GPL-2.0
summary    : GTK2 IRC Client
component  : network.irc
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpci)
    - pkgconfig(libpcre)
    - pkgconfig(lua-5.1)
    - pkgconfig(luajit)
    - pkgconfig(atk)
    - pkgconfig(pangocairo)
    - pkgconfig(atspi-2)
    - gnome-common
description: HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
