name       : hexchat
version    : 2.12.4
release    : 11
homepage   : https://hexchat.github.io/
source     :
    - https://dl.hexchat.net/hexchat/hexchat-2.12.4-repack.tar.xz : 174168d48705c2a68623246b2ab240ddc1362e45cb023b22ebd5fa7029bae0f0
license    : GPL-2.0
summary    : GTK2 IRC Client
component  : network.irc
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libpci)
    - pkgconfig(luajit)
    - pkgconfig(python3)
rundeps   :
    - enchant
description: HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
setup      : |
    %configure --enable-python=python3
build      : |
    %make
install    : |
    %make_install
